detectapp/HTF/urls.py
from django.urls import path
from . import views

app_name='htf'
urlpatterns = [
    path('', views.index, name='index'),
    path('predict/', views.predict, name='predict'),
]

detectapp/detectapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('htf/', include('HTF.urls')),
]

detectapp/HTF/models.py
from django.db import models

import sys, io, base64
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import load_model
from PIL import Image

graph = tf.get_default_graph()

class Photo(models.Model):
    image = models.ImageField(upload_to="photos")

    IMAGE_SIZE = 224
    MODEL_FILE_PATH = "./HTF/ml_models/htf_model.h5"
    classes = ["Lumpy", "Giggles", "Cuddles"]
    num_classes = len(classes)

    # 引数から画像ファイルを参照して読み込む
    def predict(self):
        model = None
        global graph
        with graph.as_default():
            model = load_model(self.MODEL_FILE_PATH)

            img_data = self.image.read()
            img_bin = io.BytesIO(img_data)

            image = Image.open(img_bin)
            image = image.convert("RGB")
            image = image.resize((self.IMAGE_SIZE, self.IMAGE_SIZE))
            data = np.asarray(image) / 255.0
            X = []
            X.append(data)
            X = np.array(X)

            result = model.predict([X])[0]
            predicted = result.argmax()
            percentage = int(result[predicted] * 100)

            return self.classes[predicted], percentage
    def image_src(self):
        with self.image.open() as img:
            base64_img = base64.b64encode(img.read()).decode()

            return 'data:' + img.file.content_type + ';base64,' + base64_img

detectapp/HTF/forms.py
from django import forms

class PhotoForm(forms.Form):
    image = forms.ImageField(widget=forms.FileInput(attrs={'class':'custom-file-input'}))

detectapp/HTF/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from .forms import PhotoForm
from .models import Photo


def index(request):
    template = loader.get_template("HTF/index.html")
    context = {"form": PhotoForm()}
    return HttpResponse(template.render(context, request))


def predict(request):
    if not request.method == "POST":
        return
        redirect("htf:index")

    form = PhotoForm(request.POST, request.FILES)
    if not form.is_valid():
        raise ValueError("Formが不正です")

    photo = Photo(image=form.cleaned_data["image"])
    predicted, percentage = photo.predict()

    template = loader.get_template("HTF/result.html")

    context = {
        "photoname": photo.image.name,
        'photo_data': photo.image_src(),
        "predicted": predicted,
        "percentage": percentage,
    }

    return HttpResponse(template.render(context, request))

detectapp/HTF/templates/HTF/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    {% load static %}
    {% load bootstrap4 %}
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'HTF/css/style.css' %}">
{% bootstrap_javascript jquery='full' %}
<title>Happy Tree Friendsのキャラクター判定！| {% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">画像判定アプリ</a>
    </nav>
    <div class="container">
        {% block content %}{% endblock %}
    </div>



</body>
</html>

detectapp/HTF/templates/HTF/index.html
{% extends 'HTF/base.html' %}
{% block title %}Happy Tree Friendsアプリメニュー{% endblock %}

{% block content %}
<div>
  <h4 class="mt-4 mb-5 border-bottom">HTF判定アプリ</h4>
  <p>画像ファイルを選択して判定ボタンを押してね！</p>
  <form action="{% url 'htf:predict' %}" method="post" class="form" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
      <div class="custom-file">
        {{ form.image }}
        <label class="custom-file-label" for="customFile">
          判定したい画像を選択してください。
        </label>
      </div>
    </div>
    <button type="submit" class="btn btn-primary">判定する！</button>
  </form>
</div>
{% endblock %}

detectapp/HTF/templates/HTF/result.html
{% extends 'HTF/base.html' %}
{% block title %}Happy Tree Friends判定結果{% endblock %}

{% block content %}
<div>
    <h4 class="mt-4 mb-5 border-bottom">HTF判定結果</h4>
    <table class="table">
        <tbody>
            <tr>
                <td>ファイル名</td>
                <td>{{ photoname }}</td>
            </tr>
            <tr>
                <td><img class="preview-img" src={{ photo_data }}></img></td>
            </tr>
            <tr>
                <td>判定ラベル</td>
                <td>{{ predicted }}</td>
            </tr>
            <tr>
                <td>判定確率</td>
                <td>{{ percentage }} %</td>
            </tr>
        </tbody>
    </table>

    <a href="{% url 'htf:index' %}" class="btn btn-primary">画像選択メニューに戻る</a>

</div>
{% endblock %}